[book]
authors = ["Tiago Caxias"]
language = "en"
multilingual = false
src = "src"
title = "Tiago Caxias' ::ff00"

[build]
build-dir = 'static'

[output.html.search]
limit-results = 20

[output.html]
default-theme = 'rust'
preferred-dark-theme = 'ayu'
no-section-label = true

[output.html.fold]
enable = true
level = 1
